### ISSUE TITLE
Project Plan Discussion

### ISSUE THREAD

**Issue by amaraneni-sairam** [amaraneni-sairam/Decentralized-certificate-verification#1]
Hi Mates,

I have created this GitHub repo for our project. I have done some research on building the mobile application for our project, so I am thinking to follow the agile model for the development. So we divide it into multiple phases and develop as per that. Please reply your suggestions, so that we can start the project by discussing the technology stack and all.
 
Thank you

**Comment by manisriii** [comment]
Hi Sairam,

As per my knowledge flutter suits best for this application, as it allows the developers to write a single codebase that can be used to create applications for multiple platforms, including iOS, Android, web, and desktop. This is achieved by using a reactive framework and a  set of customizable widgets. Also, Flutter apps are known for their excellent performance because they compile to native ARM code. This means that Flutter apps can achieve near-native performance, even though they use a single codebase.

**Comment by devenderbolla** [comment]
Hi Guys,

I too think that we can use flutter as it is most efficient for building native apps and it contains numerous inbuilt widgets 
and I do have a little bit of hands on experience on flutter so I would say that we can use Google firebase as our backend, which makes us easy to integrate authentication and realtime database in our app..

**Comment by amaraneni-sairam** [comment]
Perfect Guys, then will go with firebase as backend and flutter as our framework to develop frontend and integrate with the backend.. And then what about blockchain storage guys ? you have any idea how we can integrate it with our app, I just know that we can use solidity for that..

**Comment by manisriii** [comment]
Hello Devender,
I absolutely agree with you,  using Flutter for native app development, complemented by Google Firebase as the backend, is a wise choice. Flutter's efficiency in creating native-like interfaces with its extensive widget library, combined with your experience, sets a strong foundation. . Google Firebase simplifies development even further by allowing for simple authentication and real-time database capabilities, resulting in a smooth and feature-rich app development experience. This combination provides a powerful toolkit for developing effective and user-friendly mobile applications.

**Comment by devenderbolla** [comment]
I did some research on how we can integrate blockchain storage to flutter apps, As the flutter community and. widget library is huge I got to know that flutter library has the inbuilt package called "flutter_ipfs" that we can import to our app. IPFS is the perfect decentralized storage for our app. Please go through it once, I am giving the link below..

https://pub.dev/packages/flutter_ipfs 

> Perfect Guys, then will go with firebase as backend and flutter as our framework to develop frontend and integrate with the backend.. And then what about blockchain storage guys ? you have any idea how we can integrate it with our app, I just know that we can use solidity for that..

**Comment by manisriii** [comment]
I think it's a good idea to use the 'flutter_ipfs' package in Flutter apps. Flutter is great for building apps, and with 'flutter_ipfs,' we can add blockchain-based storage called IPFS. It helps make our apps more secure and reliable, this integration offers improved data security and durability, making it suitable for current Flutter apps."

**Comment by amaraneni-sairam** [comment]
Alright then as suggested in the assignment 2 pdf we will divide the project plan into three phases(sprints). 

Sprint 1 : Develop the admin module and test 
Sprint 2 : Develop the student module and test
Sprint 3 : Complete the full length application and test

Make sure that you guys installed the required softwares in your systems i.e,

- Flutter
-Visual studio code or Android studio

I will create a project in the firebase and share the credentials with you.


Once we implemented the authentication in our app, we will push the project in this repository as the first commit.

**Comment by manisriii** [comment]
> Alright then as suggested in the assignment 2 pdf we will divide the project plan into three phases(sprints).
> 
> Sprint 1 : Develop the admin module and test Sprint 2 : Develop the student module and test Sprint 3 : Complete the full length application and test
> 
> Make sure that you guys installed the required softwares in your systems i.e,
> 
> -Flutter -Visual studio code or Android studio
> 
> I will create a project in the firebase and share the credentials with you.
> 
> Once we implemented the authentication in our app, we will push the project in this repository as the first commit.

Yeah sounds good to me!!

**Comment by devenderbolla** [comment]
And guys me, Satish, Keerthana, Naveen and Nitisha  have worked on optional for bonus points and created as sample wire frame in Figma for the application. I am attaching the screenshot here and will invite you guys through gmail. Please have a look at the sample and inform if there are any changes.

<img width="1440" alt="Screenshot 2023-09-20 at 9 35 35 PM" src="https://github.com/amaraneni-sairam/Decentralized-certificate-verification/assets/145519551/013e95d3-b257-4d20-b56f-b112dbdcdd19">

**Comment by devenderbolla** [comment]
If all good then we will arrange a meet with TA and show the prototype.

**Comment by amaraneni-sairam** [comment]
Looks good Deva, Will arrange a meet with TA
